on:
  push:
    tags:
      - "b*"

name: Release Binaries

jobs:
  release:
    permissions:
      contents: write
      deployments: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Binaries
        run: sh ./build/index.sh

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            bin/darwin-arm64.README
            bin/darwin-x64.README
            bin/ffmpeg-darwin-arm64
            bin/ffmpeg-darwin-x64
            bin/ffmpeg-linux-arm
            bin/ffmpeg-linux-arm64
            bin/ffmpeg-linux-ia32
            bin/ffmpeg-linux-x64
            bin/ffmpeg-win32-x64
            bin/ffprobe-darwin-arm64
            bin/ffprobe-darwin-x64
            bin/ffprobe-linux-arm
            bin/ffprobe-linux-arm64
            bin/ffprobe-linux-ia32
            bin/ffprobe-linux-x64
            bin/ffprobe-win32-x64
            bin/linux-arm.LICENSE
            bin/linux-arm.README
            bin/linux-arm64.LICENSE
            bin/linux-arm64.README
            bin/linux-ia32.LICENSE
            bin/linux-ia32.README
            bin/linux-x64.LICENSE
            bin/linux-x64.README
            bin/win32-x64.LICENSE
